/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package app.campfire.network.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param progress
 * @param rssFeed The RSS feed for the series.
 */
@Serializable
data class SeriesWithProgressAndRSSOneOf(

  @SerialName(value = "progress")
  val progress: SeriesProgress? = null,

  /* The RSS feed for the series. */
  @SerialName(value = "rssFeed")
  val rssFeed: kotlin.String? = null,

)
