/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package app.campfire.network.models

import app.campfire.network.models.FileMetadata

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Represents an audio track with various properties.
 *
 * @param index The index of the audio track.
 * @param startOffset The start offset of the audio track in seconds.
 * @param duration The duration of the audio track in seconds.
 * @param title The title of the audio track.
 * @param contentUrl The URL where the audio track content is located.
 * @param mimeType The MIME type of the audio track.
 * @param codec The codec used for the audio track.
 * @param metadata 
 */
@Serializable

data class AudioTrack (

    /* The index of the audio track. */
    @SerialName(value = "index")
    val index: kotlin.Int? = null,

    /* The start offset of the audio track in seconds. */
    @SerialName(value = "startOffset")
    val startOffset: kotlin.Float? = null,

    /* The duration of the audio track in seconds. */
    @SerialName(value = "duration")
    val duration: kotlin.Float? = null,

    /* The title of the audio track. */
    @SerialName(value = "title")
    val title: kotlin.String? = null,

    /* The URL where the audio track content is located. */
    @SerialName(value = "contentUrl")
    val contentUrl: kotlin.String? = null,

    /* The MIME type of the audio track. */
    @SerialName(value = "mimeType")
    val mimeType: kotlin.String? = null,

    /* The codec used for the audio track. */
    @SerialName(value = "codec")
    val codec: kotlin.String? = null,

    @SerialName(value = "metadata")
    val metadata: FileMetadata? = null

) {


}

