/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package app.campfire.network.models

import app.campfire.network.models.LibraryItemMinified

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Series and the included library items that an author has written.
 *
 * @param id The ID of the series.
 * @param name The name of the series.
 * @param items The items in the series. Each library item's media's metadata will have a `series` attribute, a `Series Sequence`, which is the matching series.
 */
@Serializable

data class AuthorSeries (

    /* The ID of the series. */
    @SerialName(value = "id")
    val id: String,

    /* The name of the series. */
    @SerialName(value = "name")
    val name: kotlin.String? = null,

    /* The items in the series. Each library item's media's metadata will have a `series` attribute, a `Series Sequence`, which is the matching series. */
    @SerialName(value = "items")
    val items: kotlin.collections.List<LibraryItemMinified>? = null

) {


}

