/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package app.campfire.network.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A book chapter. Includes the title and timestamps.
 *
 * @param id The ID of the book chapter.
 * @param start When in the book (in seconds) the chapter starts.
 * @param end When in the book (in seconds) the chapter ends.
 * @param title The title of the chapter.
 */
@Serializable

data class BookChapter (

    /* The ID of the book chapter. */
    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    /* When in the book (in seconds) the chapter starts. */
    @SerialName(value = "start")
    val start: kotlin.Int? = null,

    /* When in the book (in seconds) the chapter ends. */
    @SerialName(value = "end")
    val end: Double,

    /* The title of the chapter. */
    @SerialName(value = "title")
    val title: kotlin.String? = null

) {


}

