/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package app.campfire.network.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param feeds
 * @param libraryId The ID of the library.
 * @param folderId The ID of the folder.
 * @param autoDownloadEpisodes Whether episodes are automatically downloaded.
 */
@Serializable
data class BulkCreatePodcastsFromOpmlFeedUrlsRequest(

  @SerialName(value = "feeds")
  val feeds: kotlin.collections.List<kotlin.String>? = null,

  /* The ID of the library. */
  @SerialName(value = "libraryId")
  val libraryId: String,

  /* The ID of the folder. */
  @SerialName(value = "folderId")
  val folderId: String,

  /* Whether episodes are automatically downloaded. */
  @SerialName(value = "autoDownloadEpisodes")
  val autoDownloadEpisodes: kotlin.Boolean? = null,

)
