/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package app.campfire.network.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param appriseApiUrl The full URL where the Apprise API to use is located.
 * @param maxFailedAttempts The maximum number of times a notification fails before being disabled.
 * @param maxNotificationQueue The maximum number of notifications in the notification queue before events are ignored.
 */
@Serializable
data class ConfigureNotificationSettingsRequest(

  /* The full URL where the Apprise API to use is located. */
  @SerialName(value = "appriseApiUrl")
  val appriseApiUrl: kotlin.String? = null,

  /* The maximum number of times a notification fails before being disabled. */
  @SerialName(value = "maxFailedAttempts")
  val maxFailedAttempts: kotlin.Int? = 5,

  /* The maximum number of notifications in the notification queue before events are ignored. */
  @SerialName(value = "maxNotificationQueue")
  val maxNotificationQueue: kotlin.Int? = null,

)
