/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package app.campfire.network.models

import app.campfire.network.models.NotificationEventName
import app.campfire.network.models.NotificationType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param eventName
 * @param urls The Apprise URLs to use for the notification.
 * @param titleTemplate The template for the notification title.
 * @param bodyTemplate The template for the notification body.
 * @param libraryId The ID of the library. Applies to all libraries if `null`.
 * @param enabled Whether the notification is enabled.
 * @param type
 */
@Serializable

data class CreateNotificationRequest (

  @SerialName(value = "eventName")
    val eventName: app.campfire.network.models.NotificationEventName,

  /* The Apprise URLs to use for the notification. */
    @SerialName(value = "urls")
    val urls: kotlin.collections.List<kotlin.String>,

  /* The template for the notification title. */
    @SerialName(value = "titleTemplate")
    val titleTemplate: kotlin.String,

  /* The template for the notification body. */
    @SerialName(value = "bodyTemplate")
    val bodyTemplate: kotlin.String,

  /* The ID of the library. Applies to all libraries if `null`. */
    @SerialName(value = "libraryId")
    val libraryId: String,

  /* Whether the notification is enabled. */
    @SerialName(value = "enabled")
    val enabled: kotlin.Boolean? = false,

  @SerialName(value = "type")
    val type: NotificationType? = NotificationType.Info

) {


}

