/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package app.campfire.network.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param width The requested width of image in pixels.
 * @param height The requested height of image in pixels. If `null`, the height is scaled to maintain aspect ratio based on the requested width.
 * @param format The requested output format.
 * @param raw Return the raw image without scaling if true.
 */
@Serializable

data class GetAuthorImageByIdRequest (

    /* The requested width of image in pixels. */
    @SerialName(value = "width")
    val width: kotlin.Int? = 400,

    /* The requested height of image in pixels. If `null`, the height is scaled to maintain aspect ratio based on the requested width. */
    @SerialName(value = "height")
    val height: kotlin.Int? = null,

    /* The requested output format. */
    @SerialName(value = "format")
    val format: kotlin.String? = "jpeg",

    /* Return the raw image without scaling if true. */
    @SerialName(value = "raw")
    val raw: kotlin.Boolean? = false

) {


}

