/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package app.campfire.network.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param downloads
 */
@Serializable
data class GetEpisodeDownloads200Response(

  @SerialName(value = "downloads")
  val downloads: kotlin.collections.List<app.campfire.network.models.PodcastEpisode>? = null,

)
