/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package app.campfire.network.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param title
 * @param feedUrl
 */
@Serializable
data class GetFeedsFromOPMLText200ResponseFeedsInner(

  @SerialName(value = "title")
  val title: kotlin.String? = null,

  @SerialName(value = "feedUrl")
  val feedUrl: kotlin.String? = null,

)
