/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package app.campfire.network.models

import app.campfire.network.models.GetFeedsFromOPMLText200ResponseFeedsInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param feeds 
 */
@Serializable

data class GetFeedsFromOPMLText200Response (

    @SerialName(value = "feeds")
    val feeds: kotlin.collections.List<GetFeedsFromOPMLText200ResponseFeedsInner>? = null

) {


}

