/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package app.campfire.network.models

import app.campfire.network.models.GetNotifications200ResponseData
import app.campfire.network.models.NotificationSettings

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param `data` 
 * @param settings 
 */
@Serializable

data class GetNotifications200Response (

    @SerialName(value = "data")
    val `data`: GetNotifications200ResponseData? = null,

    @SerialName(value = "settings")
    val settings: NotificationSettings? = null

) {


}

