/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package app.campfire.network.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param rssFeed The RSS feed URL of the podcast
 */
@Serializable

data class GetPodcastFeedRequest (

    /* The RSS feed URL of the podcast */
    @SerialName(value = "rssFeed")
    val rssFeed: kotlin.String? = null

) {


}

