/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package app.campfire.network.models

import app.campfire.network.models.MediaType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A single item on the server, like a book or podcast. Includes series sequence information.
 *
 * @param id The ID of library items after 2.3.0.
 * @param oldLibraryItemId The ID of library items on server version 2.2.23 and before.
 * @param ino The inode of the item in the file system.
 * @param libraryId The ID of the library.
 * @param folderId The ID of the folder.
 * @param path The path of the library item on the server.
 * @param relPath The path, relative to the library folder, of the library item.
 * @param isFile Whether the library item is a single file in the root of the library folder.
 * @param mtimeMs The time (in ms since POSIX epoch) when the library item was last modified on disk.
 * @param ctimeMs The time (in ms since POSIX epoch) when the library item status was changed on disk.
 * @param birthtimeMs The time (in ms since POSIX epoch) when the library item was created on disk. Will be 0 if unknown.
 * @param addedAt The time (in ms since POSIX epoch) when added to the server.
 * @param updatedAt The time (in ms since POSIX epoch) when last updated.
 * @param isMissing Whether the library item was scanned and no longer exists.
 * @param isInvalid Whether the library item was scanned and no longer has media files.
 * @param mediaType
 * @param sequence The position in the series the book is.
 */
@Serializable

data class LibraryItemSequence (

    /* The ID of library items after 2.3.0. */
    @SerialName(value = "id")
    val id: String,

    /* The ID of library items on server version 2.2.23 and before. */
    @SerialName(value = "oldLibraryItemId")
    val oldLibraryItemId: kotlin.String? = null,

    /* The inode of the item in the file system. */
    @SerialName(value = "ino")
    val ino: kotlin.String? = null,

    /* The ID of the library. */
    @SerialName(value = "libraryId")
    val libraryId: String,

    /* The ID of the folder. */
    @SerialName(value = "folderId")
    val folderId: String,

    /* The path of the library item on the server. */
    @SerialName(value = "path")
    val path: kotlin.String? = null,

    /* The path, relative to the library folder, of the library item. */
    @SerialName(value = "relPath")
    val relPath: kotlin.String? = null,

    /* Whether the library item is a single file in the root of the library folder. */
    @SerialName(value = "isFile")
    val isFile: kotlin.Boolean? = null,

    /* The time (in ms since POSIX epoch) when the library item was last modified on disk. */
    @SerialName(value = "mtimeMs")
    val mtimeMs: kotlin.Int? = null,

    /* The time (in ms since POSIX epoch) when the library item status was changed on disk. */
    @SerialName(value = "ctimeMs")
    val ctimeMs: kotlin.Int? = null,

    /* The time (in ms since POSIX epoch) when the library item was created on disk. Will be 0 if unknown. */
    @SerialName(value = "birthtimeMs")
    val birthtimeMs: kotlin.Int? = null,

    /* The time (in ms since POSIX epoch) when added to the server. */
    @SerialName(value = "addedAt")
    val addedAt: kotlin.Int? = null,

    /* The time (in ms since POSIX epoch) when last updated. */
    @SerialName(value = "updatedAt")
    val updatedAt: kotlin.Int? = null,

    /* Whether the library item was scanned and no longer exists. */
    @SerialName(value = "isMissing")
    val isMissing: kotlin.Boolean? = null,

    /* Whether the library item was scanned and no longer has media files. */
    @SerialName(value = "isInvalid")
    val isInvalid: kotlin.Boolean? = null,

    @SerialName(value = "mediaType")
    val mediaType: MediaType? = null,

    /* The position in the series the book is. */
    @SerialName(value = "sequence")
    val sequence: kotlin.String? = null

) {


}

