/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package app.campfire.network.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param id The ID of the notification.
 * @param appriseType The type of Apprise that will be used. At the moment, only api is available.
 * @param appriseApiUrl The full URL where the Apprise API to use is located.
 * @param notifications The set notifications.
 * @param maxFailedAttempts The maximum number of times a notification fails before being disabled.
 * @param maxNotificationQueue The maximum number of notifications in the notification queue before events are ignored.
 * @param notificationDelay The time (in ms) between notification pushes.
 */
@Serializable
data class NotificationSettings(

  /* The ID of the notification. */
  @SerialName(value = "id")
  val id: kotlin.String? = null,

  /* The type of Apprise that will be used. At the moment, only api is available. */
  @SerialName(value = "appriseType")
  val appriseType: kotlin.String? = null,

  /* The full URL where the Apprise API to use is located. */
  @SerialName(value = "appriseApiUrl")
  val appriseApiUrl: kotlin.String? = null,

  /* The set notifications. */
  @SerialName(value = "notifications")
  val notifications: kotlin.collections.List<Notification>? = null,

  /* The maximum number of times a notification fails before being disabled. */
  @SerialName(value = "maxFailedAttempts")
  val maxFailedAttempts: kotlin.Int? = 5,

  /* The maximum number of notifications in the notification queue before events are ignored. */
  @SerialName(value = "maxNotificationQueue")
  val maxNotificationQueue: kotlin.Int? = null,

  /* The time (in ms) between notification pushes. */
  @SerialName(value = "notificationDelay")
  val notificationDelay: kotlin.Int? = null,

)
