/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package app.campfire.network.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param numEpisodesUpdated
 */
@Serializable
data class QuickMatchEpisodes200Response(

  @SerialName(value = "numEpisodesUpdated")
  val numEpisodesUpdated: kotlin.Int? = null,

)
