/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package app.campfire.network.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param libraryItemId The ID of library items after 2.3.0.
 * @param deviceName The name of the e-reader device.
 */
@Serializable
data class SendEBookToDeviceRequest(

  /* The ID of library items after 2.3.0. */
  @SerialName(value = "libraryItemId")
  val libraryItemId: String,

  /* The name of the e-reader device. */
  @SerialName(value = "deviceName")
  val deviceName: kotlin.String? = null,

)
