/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package app.campfire.network.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param libraryId The ID of the library.
 * @param eventName
 * @param urls The Apprise URLs to use for the notification.
 * @param titleTemplate The template for the notification title.
 * @param bodyTemplate The template for the notification body.
 * @param enabled Whether the notification is enabled.
 * @param type
 */
@Serializable
data class UpdateNotificationRequest(

  /* The ID of the library. */
  @SerialName(value = "libraryId")
  val libraryId: String,

  @SerialName(value = "eventName")
  val eventName: app.campfire.network.models.NotificationEventName? = null,

  /* The Apprise URLs to use for the notification. */
  @SerialName(value = "urls")
  val urls: kotlin.collections.List<kotlin.String>? = null,

  /* The template for the notification title. */
  @SerialName(value = "titleTemplate")
  val titleTemplate: kotlin.String? = null,

  /* The template for the notification body. */
  @SerialName(value = "bodyTemplate")
  val bodyTemplate: kotlin.String? = null,

  /* Whether the notification is enabled. */
  @SerialName(value = "enabled")
  val enabled: kotlin.Boolean? = false,

  @SerialName(value = "type")
  val type: NotificationType? = NotificationType.Info,

)
