/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package app.campfire.network.models

import app.campfire.network.models.EreaderDeviceObject

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param ereaderDevices 
 */
@Serializable

data class UpdateEReaderDevicesRequest (

    @SerialName(value = "ereaderDevices")
    val ereaderDevices: kotlin.collections.List<EreaderDeviceObject>? = null

) {


}

