/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package app.campfire.network.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param ereaderDevices
 */
@Serializable
data class UpdateEReaderDevicesRequest(

  @SerialName(value = "ereaderDevices")
  val ereaderDevices: kotlin.collections.List<EreaderDeviceObject>? = null,

)
