package app.campfire.common.compose.theme.alt

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import app.campfire.common.compose.theme.ColorPalette

private val primaryLight = Color(0xFF006D3B)
private val onPrimaryLight = Color(0xFFFFFFFF)
private val primaryContainerLight = Color(0xFF6FDE96)
private val onPrimaryContainerLight = Color(0xFF006134)
private val secondaryLight = Color(0xFF3F674B)
private val onSecondaryLight = Color(0xFFFFFFFF)
private val secondaryContainerLight = Color(0xFFBEEAC7)
private val onSecondaryContainerLight = Color(0xFF436B4F)
private val tertiaryLight = Color(0xFF006780)
private val onTertiaryLight = Color(0xFFFFFFFF)
private val tertiaryContainerLight = Color(0xFF5BD7FF)
private val onTertiaryContainerLight = Color(0xFF005C72)
private val errorLight = Color(0xFFBA1A1A)
private val onErrorLight = Color(0xFFFFFFFF)
private val errorContainerLight = Color(0xFFFFDAD6)
private val onErrorContainerLight = Color(0xFF93000A)
private val backgroundLight = Color(0xFFF5FBF2)
private val onBackgroundLight = Color(0xFF171D18)
private val surfaceLight = Color(0xFFF5FBF2)
private val onSurfaceLight = Color(0xFF171D18)
private val surfaceVariantLight = Color(0xFFD9E6D8)
private val onSurfaceVariantLight = Color(0xFF3E4A40)
private val outlineLight = Color(0xFF6E7A6F)
private val outlineVariantLight = Color(0xFFBDCABD)
private val scrimLight = Color(0xFF000000)
private val inverseSurfaceLight = Color(0xFF2C322C)
private val inverseOnSurfaceLight = Color(0xFFECF2EA)
private val inversePrimaryLight = Color(0xFF6DDC94)
private val surfaceDimLight = Color(0xFFD6DCD3)
private val surfaceBrightLight = Color(0xFFF5FBF2)
private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
private val surfaceContainerLowLight = Color(0xFFEFF5ED)
private val surfaceContainerLight = Color(0xFFEAF0E7)
private val surfaceContainerHighLight = Color(0xFFE4EAE1)
private val surfaceContainerHighestLight = Color(0xFFDEE4DC)

private val primaryLightMediumContrast = Color(0xFF003F20)
private val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
private val primaryContainerLightMediumContrast = Color(0xFF007E45)
private val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryLightMediumContrast = Color(0xFF163E25)
private val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightMediumContrast = Color(0xFF4E7659)
private val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryLightMediumContrast = Color(0xFF003C4B)
private val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightMediumContrast = Color(0xFF007793)
private val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val errorLightMediumContrast = Color(0xFF740006)
private val onErrorLightMediumContrast = Color(0xFFFFFFFF)
private val errorContainerLightMediumContrast = Color(0xFFCF2C27)
private val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
private val backgroundLightMediumContrast = Color(0xFFF5FBF2)
private val onBackgroundLightMediumContrast = Color(0xFF171D18)
private val surfaceLightMediumContrast = Color(0xFFF5FBF2)
private val onSurfaceLightMediumContrast = Color(0xFF0D130E)
private val surfaceVariantLightMediumContrast = Color(0xFFD9E6D8)
private val onSurfaceVariantLightMediumContrast = Color(0xFF2E3930)
private val outlineLightMediumContrast = Color(0xFF4A554B)
private val outlineVariantLightMediumContrast = Color(0xFF647065)
private val scrimLightMediumContrast = Color(0xFF000000)
private val inverseSurfaceLightMediumContrast = Color(0xFF2C322C)
private val inverseOnSurfaceLightMediumContrast = Color(0xFFECF2EA)
private val inversePrimaryLightMediumContrast = Color(0xFF6DDC94)
private val surfaceDimLightMediumContrast = Color(0xFFC2C8C0)
private val surfaceBrightLightMediumContrast = Color(0xFFF5FBF2)
private val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightMediumContrast = Color(0xFFEFF5ED)
private val surfaceContainerLightMediumContrast = Color(0xFFE4EAE1)
private val surfaceContainerHighLightMediumContrast = Color(0xFFD8DFD6)
private val surfaceContainerHighestLightMediumContrast = Color(0xFFCDD3CB)

private val primaryLightHighContrast = Color(0xFF003419)
private val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
private val primaryContainerLightHighContrast = Color(0xFF00552D)
private val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val secondaryLightHighContrast = Color(0xFF0A331B)
private val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightHighContrast = Color(0xFF2A5137)
private val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryLightHighContrast = Color(0xFF00313E)
private val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightHighContrast = Color(0xFF005064)
private val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val errorLightHighContrast = Color(0xFF600004)
private val onErrorLightHighContrast = Color(0xFFFFFFFF)
private val errorContainerLightHighContrast = Color(0xFF98000A)
private val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
private val backgroundLightHighContrast = Color(0xFFF5FBF2)
private val onBackgroundLightHighContrast = Color(0xFF171D18)
private val surfaceLightHighContrast = Color(0xFFF5FBF2)
private val onSurfaceLightHighContrast = Color(0xFF000000)
private val surfaceVariantLightHighContrast = Color(0xFFD9E6D8)
private val onSurfaceVariantLightHighContrast = Color(0xFF000000)
private val outlineLightHighContrast = Color(0xFF242F26)
private val outlineVariantLightHighContrast = Color(0xFF404C42)
private val scrimLightHighContrast = Color(0xFF000000)
private val inverseSurfaceLightHighContrast = Color(0xFF2C322C)
private val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
private val inversePrimaryLightHighContrast = Color(0xFF6DDC94)
private val surfaceDimLightHighContrast = Color(0xFFB4BAB3)
private val surfaceBrightLightHighContrast = Color(0xFFF5FBF2)
private val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightHighContrast = Color(0xFFECF2EA)
private val surfaceContainerLightHighContrast = Color(0xFFDEE4DC)
private val surfaceContainerHighLightHighContrast = Color(0xFFD0D6CE)
private val surfaceContainerHighestLightHighContrast = Color(0xFFC2C8C0)

private val primaryDark = Color(0xFF8BFBB0)
private val onPrimaryDark = Color(0xFF00391C)
private val primaryContainerDark = Color(0xFF6FDE96)
private val onPrimaryContainerDark = Color(0xFF006134)
private val secondaryDark = Color(0xFFA5D1AE)
private val onSecondaryDark = Color(0xFF0F381F)
private val secondaryContainerDark = Color(0xFF284F34)
private val onSecondaryContainerDark = Color(0xFF94BF9E)
private val tertiaryDark = Color(0xFFBDECFF)
private val onTertiaryDark = Color(0xFF003543)
private val tertiaryContainerDark = Color(0xFF5BD7FF)
private val onTertiaryContainerDark = Color(0xFF005C72)
private val errorDark = Color(0xFFFFB4AB)
private val onErrorDark = Color(0xFF690005)
private val errorContainerDark = Color(0xFF93000A)
private val onErrorContainerDark = Color(0xFFFFDAD6)
private val backgroundDark = Color(0xFF0F1510)
private val onBackgroundDark = Color(0xFFDEE4DC)
private val surfaceDark = Color(0xFF0F1510)
private val onSurfaceDark = Color(0xFFDEE4DC)
private val surfaceVariantDark = Color(0xFF3E4A40)
private val onSurfaceVariantDark = Color(0xFFBDCABD)
private val outlineDark = Color(0xFF879488)
private val outlineVariantDark = Color(0xFF3E4A40)
private val scrimDark = Color(0xFF000000)
private val inverseSurfaceDark = Color(0xFFDEE4DC)
private val inverseOnSurfaceDark = Color(0xFF2C322C)
private val inversePrimaryDark = Color(0xFF006D3B)
private val surfaceDimDark = Color(0xFF0F1510)
private val surfaceBrightDark = Color(0xFF353B35)
private val surfaceContainerLowestDark = Color(0xFF0A100B)
private val surfaceContainerLowDark = Color(0xFF171D18)
private val surfaceContainerDark = Color(0xFF1B211C)
private val surfaceContainerHighDark = Color(0xFF252B26)
private val surfaceContainerHighestDark = Color(0xFF303631)

private val primaryDarkMediumContrast = Color(0xFF8BFBB0)
private val onPrimaryDarkMediumContrast = Color(0xFF003318)
private val primaryContainerDarkMediumContrast = Color(0xFF6FDE96)
private val onPrimaryContainerDarkMediumContrast = Color(0xFF004121)
private val secondaryDarkMediumContrast = Color(0xFFBBE7C4)
private val onSecondaryDarkMediumContrast = Color(0xFF022C15)
private val secondaryContainerDarkMediumContrast = Color(0xFF719A7B)
private val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
private val tertiaryDarkMediumContrast = Color(0xFFBDECFF)
private val onTertiaryDarkMediumContrast = Color(0xFF00303D)
private val tertiaryContainerDarkMediumContrast = Color(0xFF5BD7FF)
private val onTertiaryContainerDarkMediumContrast = Color(0xFF003D4D)
private val errorDarkMediumContrast = Color(0xFFFFD2CC)
private val onErrorDarkMediumContrast = Color(0xFF540003)
private val errorContainerDarkMediumContrast = Color(0xFFFF5449)
private val onErrorContainerDarkMediumContrast = Color(0xFF000000)
private val backgroundDarkMediumContrast = Color(0xFF0F1510)
private val onBackgroundDarkMediumContrast = Color(0xFFDEE4DC)
private val surfaceDarkMediumContrast = Color(0xFF0F1510)
private val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
private val surfaceVariantDarkMediumContrast = Color(0xFF3E4A40)
private val onSurfaceVariantDarkMediumContrast = Color(0xFFD3E0D2)
private val outlineDarkMediumContrast = Color(0xFFA8B5A9)
private val outlineVariantDarkMediumContrast = Color(0xFF879488)
private val scrimDarkMediumContrast = Color(0xFF000000)
private val inverseSurfaceDarkMediumContrast = Color(0xFFDEE4DC)
private val inverseOnSurfaceDarkMediumContrast = Color(0xFF252C26)
private val inversePrimaryDarkMediumContrast = Color(0xFF00542C)
private val surfaceDimDarkMediumContrast = Color(0xFF0F1510)
private val surfaceBrightDarkMediumContrast = Color(0xFF404640)
private val surfaceContainerLowestDarkMediumContrast = Color(0xFF040805)
private val surfaceContainerLowDarkMediumContrast = Color(0xFF191F1A)
private val surfaceContainerDarkMediumContrast = Color(0xFF232924)
private val surfaceContainerHighDarkMediumContrast = Color(0xFF2E342E)
private val surfaceContainerHighestDarkMediumContrast = Color(0xFF393F39)

private val primaryDarkHighContrast = Color(0xFFBFFFCE)
private val onPrimaryDarkHighContrast = Color(0xFF000000)
private val primaryContainerDarkHighContrast = Color(0xFF6FDE96)
private val onPrimaryContainerDarkHighContrast = Color(0xFF001808)
private val secondaryDarkHighContrast = Color(0xFFCEFBD7)
private val onSecondaryDarkHighContrast = Color(0xFF000000)
private val secondaryContainerDarkHighContrast = Color(0xFFA2CDAB)
private val onSecondaryContainerDarkHighContrast = Color(0xFF000F04)
private val tertiaryDarkHighContrast = Color(0xFFDBF4FF)
private val onTertiaryDarkHighContrast = Color(0xFF000000)
private val tertiaryContainerDarkHighContrast = Color(0xFF5BD7FF)
private val onTertiaryContainerDarkHighContrast = Color(0xFF00161E)
private val errorDarkHighContrast = Color(0xFFFFECE9)
private val onErrorDarkHighContrast = Color(0xFF000000)
private val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
private val onErrorContainerDarkHighContrast = Color(0xFF220001)
private val backgroundDarkHighContrast = Color(0xFF0F1510)
private val onBackgroundDarkHighContrast = Color(0xFFDEE4DC)
private val surfaceDarkHighContrast = Color(0xFF0F1510)
private val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
private val surfaceVariantDarkHighContrast = Color(0xFF3E4A40)
private val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
private val outlineDarkHighContrast = Color(0xFFE6F3E6)
private val outlineVariantDarkHighContrast = Color(0xFFB9C6B9)
private val scrimDarkHighContrast = Color(0xFF000000)
private val inverseSurfaceDarkHighContrast = Color(0xFFDEE4DC)
private val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
private val inversePrimaryDarkHighContrast = Color(0xFF00542C)
private val surfaceDimDarkHighContrast = Color(0xFF0F1510)
private val surfaceBrightDarkHighContrast = Color(0xFF4B524B)
private val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
private val surfaceContainerLowDarkHighContrast = Color(0xFF1B211C)
private val surfaceContainerDarkHighContrast = Color(0xFF2C322C)
private val surfaceContainerHighDarkHighContrast = Color(0xFF373D37)
private val surfaceContainerHighestDarkHighContrast = Color(0xFF424842)

private val lightScheme = lightColorScheme(
  primary = primaryLight,
  onPrimary = onPrimaryLight,
  primaryContainer = primaryContainerLight,
  onPrimaryContainer = onPrimaryContainerLight,
  secondary = secondaryLight,
  onSecondary = onSecondaryLight,
  secondaryContainer = secondaryContainerLight,
  onSecondaryContainer = onSecondaryContainerLight,
  tertiary = tertiaryLight,
  onTertiary = onTertiaryLight,
  tertiaryContainer = tertiaryContainerLight,
  onTertiaryContainer = onTertiaryContainerLight,
  error = errorLight,
  onError = onErrorLight,
  errorContainer = errorContainerLight,
  onErrorContainer = onErrorContainerLight,
  background = backgroundLight,
  onBackground = onBackgroundLight,
  surface = surfaceLight,
  onSurface = onSurfaceLight,
  surfaceVariant = surfaceVariantLight,
  onSurfaceVariant = onSurfaceVariantLight,
  outline = outlineLight,
  outlineVariant = outlineVariantLight,
  scrim = scrimLight,
  inverseSurface = inverseSurfaceLight,
  inverseOnSurface = inverseOnSurfaceLight,
  inversePrimary = inversePrimaryLight,
  surfaceDim = surfaceDimLight,
  surfaceBright = surfaceBrightLight,
  surfaceContainerLowest = surfaceContainerLowestLight,
  surfaceContainerLow = surfaceContainerLowLight,
  surfaceContainer = surfaceContainerLight,
  surfaceContainerHigh = surfaceContainerHighLight,
  surfaceContainerHighest = surfaceContainerHighestLight,
)

private val darkScheme = darkColorScheme(
  primary = primaryDark,
  onPrimary = onPrimaryDark,
  primaryContainer = primaryContainerDark,
  onPrimaryContainer = onPrimaryContainerDark,
  secondary = secondaryDark,
  onSecondary = onSecondaryDark,
  secondaryContainer = secondaryContainerDark,
  onSecondaryContainer = onSecondaryContainerDark,
  tertiary = tertiaryDark,
  onTertiary = onTertiaryDark,
  tertiaryContainer = tertiaryContainerDark,
  onTertiaryContainer = onTertiaryContainerDark,
  error = errorDark,
  onError = onErrorDark,
  errorContainer = errorContainerDark,
  onErrorContainer = onErrorContainerDark,
  background = backgroundDark,
  onBackground = onBackgroundDark,
  surface = surfaceDark,
  onSurface = onSurfaceDark,
  surfaceVariant = surfaceVariantDark,
  onSurfaceVariant = onSurfaceVariantDark,
  outline = outlineDark,
  outlineVariant = outlineVariantDark,
  scrim = scrimDark,
  inverseSurface = inverseSurfaceDark,
  inverseOnSurface = inverseOnSurfaceDark,
  inversePrimary = inversePrimaryDark,
  surfaceDim = surfaceDimDark,
  surfaceBright = surfaceBrightDark,
  surfaceContainerLowest = surfaceContainerLowestDark,
  surfaceContainerLow = surfaceContainerLowDark,
  surfaceContainer = surfaceContainerDark,
  surfaceContainerHigh = surfaceContainerHighDark,
  surfaceContainerHighest = surfaceContainerHighestDark,
)

private val mediumContrastLightColorScheme = lightColorScheme(
  primary = primaryLightMediumContrast,
  onPrimary = onPrimaryLightMediumContrast,
  primaryContainer = primaryContainerLightMediumContrast,
  onPrimaryContainer = onPrimaryContainerLightMediumContrast,
  secondary = secondaryLightMediumContrast,
  onSecondary = onSecondaryLightMediumContrast,
  secondaryContainer = secondaryContainerLightMediumContrast,
  onSecondaryContainer = onSecondaryContainerLightMediumContrast,
  tertiary = tertiaryLightMediumContrast,
  onTertiary = onTertiaryLightMediumContrast,
  tertiaryContainer = tertiaryContainerLightMediumContrast,
  onTertiaryContainer = onTertiaryContainerLightMediumContrast,
  error = errorLightMediumContrast,
  onError = onErrorLightMediumContrast,
  errorContainer = errorContainerLightMediumContrast,
  onErrorContainer = onErrorContainerLightMediumContrast,
  background = backgroundLightMediumContrast,
  onBackground = onBackgroundLightMediumContrast,
  surface = surfaceLightMediumContrast,
  onSurface = onSurfaceLightMediumContrast,
  surfaceVariant = surfaceVariantLightMediumContrast,
  onSurfaceVariant = onSurfaceVariantLightMediumContrast,
  outline = outlineLightMediumContrast,
  outlineVariant = outlineVariantLightMediumContrast,
  scrim = scrimLightMediumContrast,
  inverseSurface = inverseSurfaceLightMediumContrast,
  inverseOnSurface = inverseOnSurfaceLightMediumContrast,
  inversePrimary = inversePrimaryLightMediumContrast,
  surfaceDim = surfaceDimLightMediumContrast,
  surfaceBright = surfaceBrightLightMediumContrast,
  surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
  surfaceContainerLow = surfaceContainerLowLightMediumContrast,
  surfaceContainer = surfaceContainerLightMediumContrast,
  surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
  surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
)

private val highContrastLightColorScheme = lightColorScheme(
  primary = primaryLightHighContrast,
  onPrimary = onPrimaryLightHighContrast,
  primaryContainer = primaryContainerLightHighContrast,
  onPrimaryContainer = onPrimaryContainerLightHighContrast,
  secondary = secondaryLightHighContrast,
  onSecondary = onSecondaryLightHighContrast,
  secondaryContainer = secondaryContainerLightHighContrast,
  onSecondaryContainer = onSecondaryContainerLightHighContrast,
  tertiary = tertiaryLightHighContrast,
  onTertiary = onTertiaryLightHighContrast,
  tertiaryContainer = tertiaryContainerLightHighContrast,
  onTertiaryContainer = onTertiaryContainerLightHighContrast,
  error = errorLightHighContrast,
  onError = onErrorLightHighContrast,
  errorContainer = errorContainerLightHighContrast,
  onErrorContainer = onErrorContainerLightHighContrast,
  background = backgroundLightHighContrast,
  onBackground = onBackgroundLightHighContrast,
  surface = surfaceLightHighContrast,
  onSurface = onSurfaceLightHighContrast,
  surfaceVariant = surfaceVariantLightHighContrast,
  onSurfaceVariant = onSurfaceVariantLightHighContrast,
  outline = outlineLightHighContrast,
  outlineVariant = outlineVariantLightHighContrast,
  scrim = scrimLightHighContrast,
  inverseSurface = inverseSurfaceLightHighContrast,
  inverseOnSurface = inverseOnSurfaceLightHighContrast,
  inversePrimary = inversePrimaryLightHighContrast,
  surfaceDim = surfaceDimLightHighContrast,
  surfaceBright = surfaceBrightLightHighContrast,
  surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
  surfaceContainerLow = surfaceContainerLowLightHighContrast,
  surfaceContainer = surfaceContainerLightHighContrast,
  surfaceContainerHigh = surfaceContainerHighLightHighContrast,
  surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
)

private val mediumContrastDarkColorScheme = darkColorScheme(
  primary = primaryDarkMediumContrast,
  onPrimary = onPrimaryDarkMediumContrast,
  primaryContainer = primaryContainerDarkMediumContrast,
  onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
  secondary = secondaryDarkMediumContrast,
  onSecondary = onSecondaryDarkMediumContrast,
  secondaryContainer = secondaryContainerDarkMediumContrast,
  onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
  tertiary = tertiaryDarkMediumContrast,
  onTertiary = onTertiaryDarkMediumContrast,
  tertiaryContainer = tertiaryContainerDarkMediumContrast,
  onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
  error = errorDarkMediumContrast,
  onError = onErrorDarkMediumContrast,
  errorContainer = errorContainerDarkMediumContrast,
  onErrorContainer = onErrorContainerDarkMediumContrast,
  background = backgroundDarkMediumContrast,
  onBackground = onBackgroundDarkMediumContrast,
  surface = surfaceDarkMediumContrast,
  onSurface = onSurfaceDarkMediumContrast,
  surfaceVariant = surfaceVariantDarkMediumContrast,
  onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
  outline = outlineDarkMediumContrast,
  outlineVariant = outlineVariantDarkMediumContrast,
  scrim = scrimDarkMediumContrast,
  inverseSurface = inverseSurfaceDarkMediumContrast,
  inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
  inversePrimary = inversePrimaryDarkMediumContrast,
  surfaceDim = surfaceDimDarkMediumContrast,
  surfaceBright = surfaceBrightDarkMediumContrast,
  surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
  surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
  surfaceContainer = surfaceContainerDarkMediumContrast,
  surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
  surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
)

private val highContrastDarkColorScheme = darkColorScheme(
  primary = primaryDarkHighContrast,
  onPrimary = onPrimaryDarkHighContrast,
  primaryContainer = primaryContainerDarkHighContrast,
  onPrimaryContainer = onPrimaryContainerDarkHighContrast,
  secondary = secondaryDarkHighContrast,
  onSecondary = onSecondaryDarkHighContrast,
  secondaryContainer = secondaryContainerDarkHighContrast,
  onSecondaryContainer = onSecondaryContainerDarkHighContrast,
  tertiary = tertiaryDarkHighContrast,
  onTertiary = onTertiaryDarkHighContrast,
  tertiaryContainer = tertiaryContainerDarkHighContrast,
  onTertiaryContainer = onTertiaryContainerDarkHighContrast,
  error = errorDarkHighContrast,
  onError = onErrorDarkHighContrast,
  errorContainer = errorContainerDarkHighContrast,
  onErrorContainer = onErrorContainerDarkHighContrast,
  background = backgroundDarkHighContrast,
  onBackground = onBackgroundDarkHighContrast,
  surface = surfaceDarkHighContrast,
  onSurface = onSurfaceDarkHighContrast,
  surfaceVariant = surfaceVariantDarkHighContrast,
  onSurfaceVariant = onSurfaceVariantDarkHighContrast,
  outline = outlineDarkHighContrast,
  outlineVariant = outlineVariantDarkHighContrast,
  scrim = scrimDarkHighContrast,
  inverseSurface = inverseSurfaceDarkHighContrast,
  inverseOnSurface = inverseOnSurfaceDarkHighContrast,
  inversePrimary = inversePrimaryDarkHighContrast,
  surfaceDim = surfaceDimDarkHighContrast,
  surfaceBright = surfaceBrightDarkHighContrast,
  surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
  surfaceContainerLow = surfaceContainerLowDarkHighContrast,
  surfaceContainer = surfaceContainerDarkHighContrast,
  surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
  surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
)

/**
 * @see app.campfire.core.model.Tent.Green
 */
val AltGreenColorPalette = ColorPalette(
  lightScheme,
  darkScheme,
  mediumContrastLightColorScheme,
  highContrastLightColorScheme,
  mediumContrastDarkColorScheme,
  highContrastDarkColorScheme,
)
