package app.campfire.common.compose.theme.alt

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import app.campfire.common.compose.theme.ColorPalette

private val Seed = Color(0xFFFF6200)

private val PrimaryLight = Color(0xFFA03B00)
private val OnPrimaryLight = Color(0xFFFFEFEA)
private val PrimaryContainerLight = Color(0xFFFF793B)
private val OnPrimaryContainerLight = Color(0xFF421400)
private val InversePrimaryLight = Color(0xFFFC6100)
private val SecondaryLight = Color(0xFF5A6000)
private val OnSecondaryLight = Color(0xFFEFFE00)
private val SecondaryContainerLight = Color(0xFFDFED00)
private val OnSecondaryContainerLight = Color(0xFF505600)
private val TertiaryLight = Color(0xFF7D5300)
private val OnTertiaryLight = Color(0xFFFFF0E1)
private val TertiaryContainerLight = Color(0xFFFCAF23)
private val OnTertiaryContainerLight = Color(0xFF513500)
private val BackgroundLight = Color(0xFFFFF4F0)
private val OnBackgroundLight = Color(0xFF4B2508)
private val SurfaceLight = Color(0xFFFFF4F0)
private val OnSurfaceLight = Color(0xFF4B2508)
private val SurfaceVariantLight = Color(0xFFFFD4BC)
private val OnSurfaceVariantLight = Color(0xFF805031)
private val SurfaceTintLight = Color(0xFFA03B00)
private val InverseSurfaceLight = Color(0xFF1D0800)
private val InverseOnSurfaceLight = Color(0xFFCA906C)
private val ErrorLight = Color(0xFFB31B25)
private val OnErrorLight = Color(0xFFFFEFEE)
private val ErrorContainerLight = Color(0xFFFB5151)
private val OnErrorContainerLight = Color(0xFF570008)
private val OutlineLight = Color(0xFF9F6B49)
private val OutlineVariantLight = Color(0xFFE89C6B)
private val ScrimLight = Color(0xFF000000)
private val SurfaceBrightLight = Color(0xFFFFF4F0)
private val SurfaceContainerLight = Color(0xFFFFE3D3)
private val SurfaceContainerHighLight = Color(0xFFFFDBC8)
private val SurfaceContainerHighestLight = Color(0xFFFFD4BC)
private val SurfaceContainerLowLight = Color(0xFFFFEDE5)
private val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
private val SurfaceDimLight = Color(0xFFFFC9A9)

private val PrimaryDark = Color(0xFFFF9060)
private val OnPrimaryDark = Color(0xFF551C00)
private val PrimaryContainerDark = Color(0xFFFF793B)
private val OnPrimaryContainerDark = Color(0xFF421400)
private val InversePrimaryDark = Color(0xFFA63D00)
private val SecondaryDark = Color(0xFFDFED00)
private val OnSecondaryDark = Color(0xFF505600)
private val SecondaryContainerDark = Color(0xFF5D6300)
private val OnSecondaryContainerDark = Color(0xFFF7FF94)
private val TertiaryDark = Color(0xFFFFC162)
private val OnTertiaryDark = Color(0xFF5E3D00)
private val TertiaryContainerDark = Color(0xFFFCAF23)
private val OnTertiaryContainerDark = Color(0xFF513500)
private val BackgroundDark = Color(0xFF1D0800)
private val OnBackgroundDark = Color(0xFFFFDFCE)
private val SurfaceDark = Color(0xFF1D0800)
private val OnSurfaceDark = Color(0xFFFFDFCE)
private val SurfaceVariantDark = Color(0xFF411B00)
private val OnSurfaceVariantDark = Color(0xFFDA9E78)
private val SurfaceTintDark = Color(0xFFFF9060)
private val InverseSurfaceDark = Color(0xFFFFF8F5)
private val InverseOnSurfaceDark = Color(0xFF784A2B)
private val ErrorDark = Color(0xFFFF716C)
private val OnErrorDark = Color(0xFF490006)
private val ErrorContainerDark = Color(0xFF9F0519)
private val OnErrorContainerDark = Color(0xFFFFA8A3)
private val OutlineDark = Color(0xFF9E6948)
private val OutlineVariantDark = Color(0xFF703910)
private val ScrimDark = Color(0xFF000000)
private val SurfaceBrightDark = Color(0xFF4B2000)
private val SurfaceContainerDark = Color(0xFF2E1100)
private val SurfaceContainerHighDark = Color(0xFF381600)
private val SurfaceContainerHighestDark = Color(0xFF411B00)
private val SurfaceContainerLowDark = Color(0xFF250C00)
private val SurfaceContainerLowestDark = Color(0xFF000000)
private val SurfaceDimDark = Color(0xFF1D0800)

private val PrimaryFixed = Color(0xFFFF793B)
private val PrimaryFixedDim = Color(0xFFFC6100)
private val OnPrimaryFixed = Color(0xFF000000)
private val OnPrimaryFixedVariant = Color(0xFF521A00)
private val SecondaryFixed = Color(0xFFDFED00)
private val SecondaryFixedDim = Color(0xFFD1DE00)
private val OnSecondaryFixed = Color(0xFF3E4300)
private val OnSecondaryFixedVariant = Color(0xFF5A6000)
private val TertiaryFixed = Color(0xFFFCAF23)
private val TertiaryFixedDim = Color(0xFFECA210)
private val OnTertiaryFixed = Color(0xFF362100)
private val OnTertiaryFixedVariant = Color(0xFF5D3D00)

private val lightColorScheme = lightColorScheme(
  primary = PrimaryLight,
  onPrimary = OnPrimaryLight,
  primaryContainer = PrimaryContainerLight,
  onPrimaryContainer = OnPrimaryContainerLight,
  inversePrimary = InversePrimaryLight,
  secondary = SecondaryLight,
  onSecondary = OnSecondaryLight,
  secondaryContainer = SecondaryContainerLight,
  onSecondaryContainer = OnSecondaryContainerLight,
  tertiary = TertiaryLight,
  onTertiary = OnTertiaryLight,
  tertiaryContainer = TertiaryContainerLight,
  onTertiaryContainer = OnTertiaryContainerLight,
  background = BackgroundLight,
  onBackground = OnBackgroundLight,
  surface = SurfaceLight,
  onSurface = OnSurfaceLight,
  surfaceVariant = SurfaceVariantLight,
  onSurfaceVariant = OnSurfaceVariantLight,
  surfaceTint = SurfaceTintLight,
  inverseSurface = InverseSurfaceLight,
  inverseOnSurface = InverseOnSurfaceLight,
  error = ErrorLight,
  onError = OnErrorLight,
  errorContainer = ErrorContainerLight,
  onErrorContainer = OnErrorContainerLight,
  outline = OutlineLight,
  outlineVariant = OutlineVariantLight,
  scrim = ScrimLight,
  surfaceBright = SurfaceBrightLight,
  surfaceContainer = SurfaceContainerLight,
  surfaceContainerHigh = SurfaceContainerHighLight,
  surfaceContainerHighest = SurfaceContainerHighestLight,
  surfaceContainerLow = SurfaceContainerLowLight,
  surfaceContainerLowest = SurfaceContainerLowestLight,
  surfaceDim = SurfaceDimLight,
  primaryFixed = PrimaryFixed,
  primaryFixedDim = PrimaryFixedDim,
  onPrimaryFixed = OnPrimaryFixed,
  onPrimaryFixedVariant = OnPrimaryFixedVariant,
  secondaryFixed = SecondaryFixed,
  secondaryFixedDim = SecondaryFixedDim,
  onSecondaryFixed = OnSecondaryFixed,
  onSecondaryFixedVariant = OnSecondaryFixedVariant,
  tertiaryFixed = TertiaryFixed,
  tertiaryFixedDim = TertiaryFixedDim,
  onTertiaryFixed = OnTertiaryFixed,
  onTertiaryFixedVariant = OnTertiaryFixedVariant,
)

private val darkColorScheme = darkColorScheme(
  primary = PrimaryDark,
  onPrimary = OnPrimaryDark,
  primaryContainer = PrimaryContainerDark,
  onPrimaryContainer = OnPrimaryContainerDark,
  inversePrimary = InversePrimaryDark,
  secondary = SecondaryDark,
  onSecondary = OnSecondaryDark,
  secondaryContainer = SecondaryContainerDark,
  onSecondaryContainer = OnSecondaryContainerDark,
  tertiary = TertiaryDark,
  onTertiary = OnTertiaryDark,
  tertiaryContainer = TertiaryContainerDark,
  onTertiaryContainer = OnTertiaryContainerDark,
  background = BackgroundDark,
  onBackground = OnBackgroundDark,
  surface = SurfaceDark,
  onSurface = OnSurfaceDark,
  surfaceVariant = SurfaceVariantDark,
  onSurfaceVariant = OnSurfaceVariantDark,
  surfaceTint = SurfaceTintDark,
  inverseSurface = InverseSurfaceDark,
  inverseOnSurface = InverseOnSurfaceDark,
  error = ErrorDark,
  onError = OnErrorDark,
  errorContainer = ErrorContainerDark,
  onErrorContainer = OnErrorContainerDark,
  outline = OutlineDark,
  outlineVariant = OutlineVariantDark,
  scrim = ScrimDark,
  surfaceBright = SurfaceBrightDark,
  surfaceContainer = SurfaceContainerDark,
  surfaceContainerHigh = SurfaceContainerHighDark,
  surfaceContainerHighest = SurfaceContainerHighestDark,
  surfaceContainerLow = SurfaceContainerLowDark,
  surfaceContainerLowest = SurfaceContainerLowestDark,
  surfaceDim = SurfaceDimDark,
  primaryFixed = PrimaryFixed,
  primaryFixedDim = PrimaryFixedDim,
  onPrimaryFixed = OnPrimaryFixed,
  onPrimaryFixedVariant = OnPrimaryFixedVariant,
  secondaryFixed = SecondaryFixed,
  secondaryFixedDim = SecondaryFixedDim,
  onSecondaryFixed = OnSecondaryFixed,
  onSecondaryFixedVariant = OnSecondaryFixedVariant,
  tertiaryFixed = TertiaryFixed,
  tertiaryFixedDim = TertiaryFixedDim,
  onTertiaryFixed = OnTertiaryFixed,
  onTertiaryFixedVariant = OnTertiaryFixedVariant,
)

val AltOrangeColorPalette = ColorPalette(
  lightColorScheme = lightColorScheme,
  darkColorScheme = darkColorScheme,
)
