package app.campfire.common.compose.theme.alt

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import app.campfire.common.compose.theme.ColorPalette

private val Seed = Color(0xFF8100FF)

private val PrimaryLight = Color(0xFF7A00F2)
private val OnPrimaryLight = Color(0xFFF9EFFF)
private val PrimaryContainerLight = Color(0xFFB78AFF)
private val OnPrimaryContainerLight = Color(0xFF310068)
private val InversePrimaryLight = Color(0xFFAA73FF)
private val SecondaryLight = Color(0xFF006479)
private val OnSecondaryLight = Color(0xFFE0F6FF)
private val SecondaryContainerLight = Color(0xFF77DFFF)
private val OnSecondaryContainerLight = Color(0xFF004E5F)
private val TertiaryLight = Color(0xFF9F3652)
private val OnTertiaryLight = Color(0xFFFFEFF0)
private val TertiaryContainerLight = Color(0xFFFF8FA7)
private val OnTertiaryContainerLight = Color(0xFF650528)
private val BackgroundLight = Color(0xFFFFF3FF)
private val OnBackgroundLight = Color(0xFF3B264A)
private val SurfaceLight = Color(0xFFFFF3FF)
private val OnSurfaceLight = Color(0xFF3B264A)
private val SurfaceVariantLight = Color(0xFFF0D2FF)
private val OnSurfaceVariantLight = Color(0xFF6B527A)
private val SurfaceTintLight = Color(0xFF7A00F2)
private val InverseSurfaceLight = Color(0xFF190428)
private val InverseOnSurfaceLight = Color(0xFFAF93BF)
private val ErrorLight = Color(0xFFB41340)
private val OnErrorLight = Color(0xFFFFEFEF)
private val ErrorContainerLight = Color(0xFFF74B6D)
private val OnErrorContainerLight = Color(0xFF510017)
private val OutlineLight = Color(0xFF876D97)
private val OutlineVariantLight = Color(0xFFC59FDC)
private val ScrimLight = Color(0xFF000000)
private val SurfaceBrightLight = Color(0xFFFFF3FF)
private val SurfaceContainerLight = Color(0xFFF6E1FF)
private val SurfaceContainerHighLight = Color(0xFFF3DAFF)
private val SurfaceContainerHighestLight = Color(0xFFF0D2FF)
private val SurfaceContainerLowLight = Color(0xFFFBECFF)
private val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
private val SurfaceDimLight = Color(0xFFEBC8FF)

private val PrimaryDark = Color(0xFFC29BFF)
private val OnPrimaryDark = Color(0xFF400084)
private val PrimaryContainerDark = Color(0xFFB78AFF)
private val OnPrimaryContainerDark = Color(0xFF310068)
private val InversePrimaryDark = Color(0xFF7F00FA)
private val SecondaryDark = Color(0xFF08D5FF)
private val OnSecondaryDark = Color(0xFF004554)
private val SecondaryContainerDark = Color(0xFF00677D)
private val OnSecondaryContainerDark = Color(0xFFEDFAFF)
private val TertiaryDark = Color(0xFFFF93AA)
private val OnTertiaryDark = Color(0xFF68082A)
private val TertiaryContainerDark = Color(0xFFFC7E9B)
private val OnTertiaryContainerDark = Color(0xFF560020)
private val BackgroundDark = Color(0xFF190428)
private val OnBackgroundDark = Color(0xFFF5DDFF)
private val SurfaceDark = Color(0xFF190428)
private val OnSurfaceDark = Color(0xFFF5DDFF)
private val SurfaceVariantDark = Color(0xFF36174B)
private val OnSurfaceVariantDark = Color(0xFFBDA1CD)
private val SurfaceTintDark = Color(0xFFC29BFF)
private val InverseSurfaceDark = Color(0xFFFFF7FD)
private val InverseOnSurfaceDark = Color(0xFF644C73)
private val ErrorDark = Color(0xFFFF6E84)
private val OnErrorDark = Color(0xFF490013)
private val ErrorContainerDark = Color(0xFFA70138)
private val OnErrorContainerDark = Color(0xFFFFB2B9)
private val OutlineDark = Color(0xFF866C95)
private val OutlineVariantDark = Color(0xFF5A3B70)
private val ScrimDark = Color(0xFF000000)
private val SurfaceBrightDark = Color(0xFF3D1D54)
private val SurfaceContainerDark = Color(0xFF270D39)
private val SurfaceContainerHighDark = Color(0xFF2E1242)
private val SurfaceContainerHighestDark = Color(0xFF36174B)
private val SurfaceContainerLowDark = Color(0xFF1F0730)
private val SurfaceContainerLowestDark = Color(0xFF000000)
private val SurfaceDimDark = Color(0xFF190428)

private val PrimaryFixed = Color(0xFFB78AFF)
private val PrimaryFixedDim = Color(0xFFAC77FF)
private val OnPrimaryFixed = Color(0xFF000000)
private val OnPrimaryFixedVariant = Color(0xFF3D007F)
private val SecondaryFixed = Color(0xFF77DFFF)
private val SecondaryFixedDim = Color(0xFF08D5FF)
private val OnSecondaryFixed = Color(0xFF003A47)
private val OnSecondaryFixedVariant = Color(0xFF00586B)
private val TertiaryFixed = Color(0xFFFF8FA7)
private val TertiaryFixedDim = Color(0xFFF87C98)
private val OnTertiaryFixed = Color(0xFF390013)
private val OnTertiaryFixedVariant = Color(0xFF711131)

private val lightColorScheme = lightColorScheme(
  primary = PrimaryLight,
  onPrimary = OnPrimaryLight,
  primaryContainer = PrimaryContainerLight,
  onPrimaryContainer = OnPrimaryContainerLight,
  inversePrimary = InversePrimaryLight,
  secondary = SecondaryLight,
  onSecondary = OnSecondaryLight,
  secondaryContainer = SecondaryContainerLight,
  onSecondaryContainer = OnSecondaryContainerLight,
  tertiary = TertiaryLight,
  onTertiary = OnTertiaryLight,
  tertiaryContainer = TertiaryContainerLight,
  onTertiaryContainer = OnTertiaryContainerLight,
  background = BackgroundLight,
  onBackground = OnBackgroundLight,
  surface = SurfaceLight,
  onSurface = OnSurfaceLight,
  surfaceVariant = SurfaceVariantLight,
  onSurfaceVariant = OnSurfaceVariantLight,
  surfaceTint = SurfaceTintLight,
  inverseSurface = InverseSurfaceLight,
  inverseOnSurface = InverseOnSurfaceLight,
  error = ErrorLight,
  onError = OnErrorLight,
  errorContainer = ErrorContainerLight,
  onErrorContainer = OnErrorContainerLight,
  outline = OutlineLight,
  outlineVariant = OutlineVariantLight,
  scrim = ScrimLight,
  surfaceBright = SurfaceBrightLight,
  surfaceContainer = SurfaceContainerLight,
  surfaceContainerHigh = SurfaceContainerHighLight,
  surfaceContainerHighest = SurfaceContainerHighestLight,
  surfaceContainerLow = SurfaceContainerLowLight,
  surfaceContainerLowest = SurfaceContainerLowestLight,
  surfaceDim = SurfaceDimLight,
  primaryFixed = PrimaryFixed,
  primaryFixedDim = PrimaryFixedDim,
  onPrimaryFixed = OnPrimaryFixed,
  onPrimaryFixedVariant = OnPrimaryFixedVariant,
  secondaryFixed = SecondaryFixed,
  secondaryFixedDim = SecondaryFixedDim,
  onSecondaryFixed = OnSecondaryFixed,
  onSecondaryFixedVariant = OnSecondaryFixedVariant,
  tertiaryFixed = TertiaryFixed,
  tertiaryFixedDim = TertiaryFixedDim,
  onTertiaryFixed = OnTertiaryFixed,
  onTertiaryFixedVariant = OnTertiaryFixedVariant,
)

private val darkColorScheme = darkColorScheme(
  primary = PrimaryDark,
  onPrimary = OnPrimaryDark,
  primaryContainer = PrimaryContainerDark,
  onPrimaryContainer = OnPrimaryContainerDark,
  inversePrimary = InversePrimaryDark,
  secondary = SecondaryDark,
  onSecondary = OnSecondaryDark,
  secondaryContainer = SecondaryContainerDark,
  onSecondaryContainer = OnSecondaryContainerDark,
  tertiary = TertiaryDark,
  onTertiary = OnTertiaryDark,
  tertiaryContainer = TertiaryContainerDark,
  onTertiaryContainer = OnTertiaryContainerDark,
  background = BackgroundDark,
  onBackground = OnBackgroundDark,
  surface = SurfaceDark,
  onSurface = OnSurfaceDark,
  surfaceVariant = SurfaceVariantDark,
  onSurfaceVariant = OnSurfaceVariantDark,
  surfaceTint = SurfaceTintDark,
  inverseSurface = InverseSurfaceDark,
  inverseOnSurface = InverseOnSurfaceDark,
  error = ErrorDark,
  onError = OnErrorDark,
  errorContainer = ErrorContainerDark,
  onErrorContainer = OnErrorContainerDark,
  outline = OutlineDark,
  outlineVariant = OutlineVariantDark,
  scrim = ScrimDark,
  surfaceBright = SurfaceBrightDark,
  surfaceContainer = SurfaceContainerDark,
  surfaceContainerHigh = SurfaceContainerHighDark,
  surfaceContainerHighest = SurfaceContainerHighestDark,
  surfaceContainerLow = SurfaceContainerLowDark,
  surfaceContainerLowest = SurfaceContainerLowestDark,
  surfaceDim = SurfaceDimDark,
  primaryFixed = PrimaryFixed,
  primaryFixedDim = PrimaryFixedDim,
  onPrimaryFixed = OnPrimaryFixed,
  onPrimaryFixedVariant = OnPrimaryFixedVariant,
  secondaryFixed = SecondaryFixed,
  secondaryFixedDim = SecondaryFixedDim,
  onSecondaryFixed = OnSecondaryFixed,
  onSecondaryFixedVariant = OnSecondaryFixedVariant,
  tertiaryFixed = TertiaryFixed,
  tertiaryFixedDim = TertiaryFixedDim,
  onTertiaryFixed = OnTertiaryFixed,
  onTertiaryFixedVariant = OnTertiaryFixedVariant,
)

val AltPurpleColorPalette = ColorPalette(
  lightColorScheme = lightColorScheme,
  darkColorScheme = darkColorScheme,
)
