package app.campfire.common.compose.theme.alt

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import app.campfire.common.compose.theme.ColorPalette

private val primaryLight = Color(0xFF785A00)
private val onPrimaryLight = Color(0xFFFFFFFF)
private val primaryContainerLight = Color(0xFFF8C030)
private val onPrimaryContainerLight = Color(0xFF6B4F00)
private val secondaryLight = Color(0xFF725B26)
private val onSecondaryLight = Color(0xFFFFFFFF)
private val secondaryContainerLight = Color(0xFFFFDF9D)
private val onSecondaryContainerLight = Color(0xFF79612C)
private val tertiaryLight = Color(0xFF536600)
private val onTertiaryLight = Color(0xFFFFFFFF)
private val tertiaryContainerLight = Color(0xFFB9D457)
private val onTertiaryContainerLight = Color(0xFF4A5A00)
private val errorLight = Color(0xFFBA1A1A)
private val onErrorLight = Color(0xFFFFFFFF)
private val errorContainerLight = Color(0xFFFFDAD6)
private val onErrorContainerLight = Color(0xFF93000A)
private val backgroundLight = Color(0xFFFFF8F2)
private val onBackgroundLight = Color(0xFF201B12)
private val surfaceLight = Color(0xFFFFF8F2)
private val onSurfaceLight = Color(0xFF201B12)
private val surfaceVariantLight = Color(0xFFF0E1C8)
private val onSurfaceVariantLight = Color(0xFF4F4634)
private val outlineLight = Color(0xFF817661)
private val outlineVariantLight = Color(0xFFD3C5AD)
private val scrimLight = Color(0xFF000000)
private val inverseSurfaceLight = Color(0xFF353026)
private val inverseOnSurfaceLight = Color(0xFFFAEFE0)
private val inversePrimaryLight = Color(0xFFF6BE2E)
private val surfaceDimLight = Color(0xFFE3D9CA)
private val surfaceBrightLight = Color(0xFFFFF8F2)
private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
private val surfaceContainerLowLight = Color(0xFFFDF2E3)
private val surfaceContainerLight = Color(0xFFF7ECDD)
private val surfaceContainerHighLight = Color(0xFFF1E7D7)
private val surfaceContainerHighestLight = Color(0xFFECE1D2)

private val primaryLightMediumContrast = Color(0xFF463300)
private val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
private val primaryContainerLightMediumContrast = Color(0xFF8B6800)
private val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryLightMediumContrast = Color(0xFF463301)
private val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightMediumContrast = Color(0xFF826A34)
private val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryLightMediumContrast = Color(0xFF2F3B00)
private val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightMediumContrast = Color(0xFF607500)
private val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val errorLightMediumContrast = Color(0xFF740006)
private val onErrorLightMediumContrast = Color(0xFFFFFFFF)
private val errorContainerLightMediumContrast = Color(0xFFCF2C27)
private val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
private val backgroundLightMediumContrast = Color(0xFFFFF8F2)
private val onBackgroundLightMediumContrast = Color(0xFF201B12)
private val surfaceLightMediumContrast = Color(0xFFFFF8F2)
private val onSurfaceLightMediumContrast = Color(0xFF151108)
private val surfaceVariantLightMediumContrast = Color(0xFFF0E1C8)
private val onSurfaceVariantLightMediumContrast = Color(0xFF3E3524)
private val outlineLightMediumContrast = Color(0xFF5B513F)
private val outlineVariantLightMediumContrast = Color(0xFF776C58)
private val scrimLightMediumContrast = Color(0xFF000000)
private val inverseSurfaceLightMediumContrast = Color(0xFF353026)
private val inverseOnSurfaceLightMediumContrast = Color(0xFFFAEFE0)
private val inversePrimaryLightMediumContrast = Color(0xFFF6BE2E)
private val surfaceDimLightMediumContrast = Color(0xFFCFC5B7)
private val surfaceBrightLightMediumContrast = Color(0xFFFFF8F2)
private val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightMediumContrast = Color(0xFFFDF2E3)
private val surfaceContainerLightMediumContrast = Color(0xFFF1E7D7)
private val surfaceContainerHighLightMediumContrast = Color(0xFFE6DBCC)
private val surfaceContainerHighestLightMediumContrast = Color(0xFFDAD0C1)

private val primaryLightHighContrast = Color(0xFF3A2A00)
private val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
private val primaryContainerLightHighContrast = Color(0xFF5E4500)
private val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val secondaryLightHighContrast = Color(0xFF3A2A00)
private val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightHighContrast = Color(0xFF5B4613)
private val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryLightHighContrast = Color(0xFF263000)
private val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightHighContrast = Color(0xFF404F00)
private val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val errorLightHighContrast = Color(0xFF600004)
private val onErrorLightHighContrast = Color(0xFFFFFFFF)
private val errorContainerLightHighContrast = Color(0xFF98000A)
private val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
private val backgroundLightHighContrast = Color(0xFFFFF8F2)
private val onBackgroundLightHighContrast = Color(0xFF201B12)
private val surfaceLightHighContrast = Color(0xFFFFF8F2)
private val onSurfaceLightHighContrast = Color(0xFF000000)
private val surfaceVariantLightHighContrast = Color(0xFFF0E1C8)
private val onSurfaceVariantLightHighContrast = Color(0xFF000000)
private val outlineLightHighContrast = Color(0xFF332B1B)
private val outlineVariantLightHighContrast = Color(0xFF514836)
private val scrimLightHighContrast = Color(0xFF000000)
private val inverseSurfaceLightHighContrast = Color(0xFF353026)
private val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
private val inversePrimaryLightHighContrast = Color(0xFFF6BE2E)
private val surfaceDimLightHighContrast = Color(0xFFC1B7A9)
private val surfaceBrightLightHighContrast = Color(0xFFFFF8F2)
private val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightHighContrast = Color(0xFFFAEFE0)
private val surfaceContainerLightHighContrast = Color(0xFFECE1D2)
private val surfaceContainerHighLightHighContrast = Color(0xFFDDD3C4)
private val surfaceContainerHighestLightHighContrast = Color(0xFFCFC5B7)

private val primaryDark = Color(0xFFFFE1A5)
private val onPrimaryDark = Color(0xFF3F2E00)
private val primaryContainerDark = Color(0xFFF8C030)
private val onPrimaryContainerDark = Color(0xFF6B4F00)
private val secondaryDark = Color(0xFFE1C384)
private val onSecondaryDark = Color(0xFF3F2E00)
private val secondaryContainerDark = Color(0xFF5B4613)
private val onSecondaryContainerDark = Color(0xFFD2B577)
private val tertiaryDark = Color(0xFFD5F170)
private val onTertiaryDark = Color(0xFF2A3400)
private val tertiaryContainerDark = Color(0xFFB9D457)
private val onTertiaryContainerDark = Color(0xFF4A5A00)
private val errorDark = Color(0xFFFFB4AB)
private val onErrorDark = Color(0xFF690005)
private val errorContainerDark = Color(0xFF93000A)
private val onErrorContainerDark = Color(0xFFFFDAD6)
private val backgroundDark = Color(0xFF17130A)
private val onBackgroundDark = Color(0xFFECE1D2)
private val surfaceDark = Color(0xFF17130A)
private val onSurfaceDark = Color(0xFFECE1D2)
private val surfaceVariantDark = Color(0xFF4F4634)
private val onSurfaceVariantDark = Color(0xFFD3C5AD)
private val outlineDark = Color(0xFF9B8F7A)
private val outlineVariantDark = Color(0xFF4F4634)
private val scrimDark = Color(0xFF000000)
private val inverseSurfaceDark = Color(0xFFECE1D2)
private val inverseOnSurfaceDark = Color(0xFF353026)
private val inversePrimaryDark = Color(0xFF785A00)
private val surfaceDimDark = Color(0xFF17130A)
private val surfaceBrightDark = Color(0xFF3E382E)
private val surfaceContainerLowestDark = Color(0xFF120E06)
private val surfaceContainerLowDark = Color(0xFF201B12)
private val surfaceContainerDark = Color(0xFF241F16)
private val surfaceContainerHighDark = Color(0xFF2F291F)
private val surfaceContainerHighestDark = Color(0xFF3A342A)

private val primaryDarkMediumContrast = Color(0xFFFFE1A5)
private val onPrimaryDarkMediumContrast = Color(0xFF392900)
private val primaryContainerDarkMediumContrast = Color(0xFFF8C030)
private val onPrimaryContainerDarkMediumContrast = Color(0xFF483400)
private val secondaryDarkMediumContrast = Color(0xFFF8D997)
private val onSecondaryDarkMediumContrast = Color(0xFF322300)
private val secondaryContainerDarkMediumContrast = Color(0xFFA88D53)
private val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
private val tertiaryDarkMediumContrast = Color(0xFFD5F170)
private val onTertiaryDarkMediumContrast = Color(0xFF252F00)
private val tertiaryContainerDarkMediumContrast = Color(0xFFB9D457)
private val onTertiaryContainerDarkMediumContrast = Color(0xFF303C00)
private val errorDarkMediumContrast = Color(0xFFFFD2CC)
private val onErrorDarkMediumContrast = Color(0xFF540003)
private val errorContainerDarkMediumContrast = Color(0xFFFF5449)
private val onErrorContainerDarkMediumContrast = Color(0xFF000000)
private val backgroundDarkMediumContrast = Color(0xFF17130A)
private val onBackgroundDarkMediumContrast = Color(0xFFECE1D2)
private val surfaceDarkMediumContrast = Color(0xFF17130A)
private val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
private val surfaceVariantDarkMediumContrast = Color(0xFF4F4634)
private val onSurfaceVariantDarkMediumContrast = Color(0xFFE9DBC2)
private val outlineDarkMediumContrast = Color(0xFFBEB099)
private val outlineVariantDarkMediumContrast = Color(0xFF9B8F79)
private val scrimDarkMediumContrast = Color(0xFF000000)
private val inverseSurfaceDarkMediumContrast = Color(0xFFECE1D2)
private val inverseOnSurfaceDarkMediumContrast = Color(0xFF2F291F)
private val inversePrimaryDarkMediumContrast = Color(0xFF5C4400)
private val surfaceDimDarkMediumContrast = Color(0xFF17130A)
private val surfaceBrightDarkMediumContrast = Color(0xFF4A4439)
private val surfaceContainerLowestDarkMediumContrast = Color(0xFF0A0702)
private val surfaceContainerLowDarkMediumContrast = Color(0xFF221D14)
private val surfaceContainerDarkMediumContrast = Color(0xFF2C271D)
private val surfaceContainerHighDarkMediumContrast = Color(0xFF373228)
private val surfaceContainerHighestDarkMediumContrast = Color(0xFF433D32)

private val primaryDarkHighContrast = Color(0xFFFFEED1)
private val onPrimaryDarkHighContrast = Color(0xFF000000)
private val primaryContainerDarkHighContrast = Color(0xFFF8C030)
private val onPrimaryContainerDarkHighContrast = Color(0xFF1B1200)
private val secondaryDarkHighContrast = Color(0xFFFFEED1)
private val onSecondaryDarkHighContrast = Color(0xFF000000)
private val secondaryContainerDarkHighContrast = Color(0xFFDDBF80)
private val onSecondaryContainerDarkHighContrast = Color(0xFF110A00)
private val tertiaryDarkHighContrast = Color(0xFFE0FC7A)
private val onTertiaryDarkHighContrast = Color(0xFF000000)
private val tertiaryContainerDarkHighContrast = Color(0xFFB9D457)
private val onTertiaryContainerDarkHighContrast = Color(0xFF101600)
private val errorDarkHighContrast = Color(0xFFFFECE9)
private val onErrorDarkHighContrast = Color(0xFF000000)
private val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
private val onErrorContainerDarkHighContrast = Color(0xFF220001)
private val backgroundDarkHighContrast = Color(0xFF17130A)
private val onBackgroundDarkHighContrast = Color(0xFFECE1D2)
private val surfaceDarkHighContrast = Color(0xFF17130A)
private val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
private val surfaceVariantDarkHighContrast = Color(0xFF4F4634)
private val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
private val outlineDarkHighContrast = Color(0xFFFDEED5)
private val outlineVariantDarkHighContrast = Color(0xFFCFC1A9)
private val scrimDarkHighContrast = Color(0xFF000000)
private val inverseSurfaceDarkHighContrast = Color(0xFFECE1D2)
private val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
private val inversePrimaryDarkHighContrast = Color(0xFF5C4400)
private val surfaceDimDarkHighContrast = Color(0xFF17130A)
private val surfaceBrightDarkHighContrast = Color(0xFF564F44)
private val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
private val surfaceContainerLowDarkHighContrast = Color(0xFF241F16)
private val surfaceContainerDarkHighContrast = Color(0xFF353026)
private val surfaceContainerHighDarkHighContrast = Color(0xFF413B30)
private val surfaceContainerHighestDarkHighContrast = Color(0xFF4C463B)

private val lightScheme = lightColorScheme(
  primary = primaryLight,
  onPrimary = onPrimaryLight,
  primaryContainer = primaryContainerLight,
  onPrimaryContainer = onPrimaryContainerLight,
  secondary = secondaryLight,
  onSecondary = onSecondaryLight,
  secondaryContainer = secondaryContainerLight,
  onSecondaryContainer = onSecondaryContainerLight,
  tertiary = tertiaryLight,
  onTertiary = onTertiaryLight,
  tertiaryContainer = tertiaryContainerLight,
  onTertiaryContainer = onTertiaryContainerLight,
  error = errorLight,
  onError = onErrorLight,
  errorContainer = errorContainerLight,
  onErrorContainer = onErrorContainerLight,
  background = backgroundLight,
  onBackground = onBackgroundLight,
  surface = surfaceLight,
  onSurface = onSurfaceLight,
  surfaceVariant = surfaceVariantLight,
  onSurfaceVariant = onSurfaceVariantLight,
  outline = outlineLight,
  outlineVariant = outlineVariantLight,
  scrim = scrimLight,
  inverseSurface = inverseSurfaceLight,
  inverseOnSurface = inverseOnSurfaceLight,
  inversePrimary = inversePrimaryLight,
  surfaceDim = surfaceDimLight,
  surfaceBright = surfaceBrightLight,
  surfaceContainerLowest = surfaceContainerLowestLight,
  surfaceContainerLow = surfaceContainerLowLight,
  surfaceContainer = surfaceContainerLight,
  surfaceContainerHigh = surfaceContainerHighLight,
  surfaceContainerHighest = surfaceContainerHighestLight,
)

private val darkScheme = darkColorScheme(
  primary = primaryDark,
  onPrimary = onPrimaryDark,
  primaryContainer = primaryContainerDark,
  onPrimaryContainer = onPrimaryContainerDark,
  secondary = secondaryDark,
  onSecondary = onSecondaryDark,
  secondaryContainer = secondaryContainerDark,
  onSecondaryContainer = onSecondaryContainerDark,
  tertiary = tertiaryDark,
  onTertiary = onTertiaryDark,
  tertiaryContainer = tertiaryContainerDark,
  onTertiaryContainer = onTertiaryContainerDark,
  error = errorDark,
  onError = onErrorDark,
  errorContainer = errorContainerDark,
  onErrorContainer = onErrorContainerDark,
  background = backgroundDark,
  onBackground = onBackgroundDark,
  surface = surfaceDark,
  onSurface = onSurfaceDark,
  surfaceVariant = surfaceVariantDark,
  onSurfaceVariant = onSurfaceVariantDark,
  outline = outlineDark,
  outlineVariant = outlineVariantDark,
  scrim = scrimDark,
  inverseSurface = inverseSurfaceDark,
  inverseOnSurface = inverseOnSurfaceDark,
  inversePrimary = inversePrimaryDark,
  surfaceDim = surfaceDimDark,
  surfaceBright = surfaceBrightDark,
  surfaceContainerLowest = surfaceContainerLowestDark,
  surfaceContainerLow = surfaceContainerLowDark,
  surfaceContainer = surfaceContainerDark,
  surfaceContainerHigh = surfaceContainerHighDark,
  surfaceContainerHighest = surfaceContainerHighestDark,
)

private val mediumContrastLightColorScheme = lightColorScheme(
  primary = primaryLightMediumContrast,
  onPrimary = onPrimaryLightMediumContrast,
  primaryContainer = primaryContainerLightMediumContrast,
  onPrimaryContainer = onPrimaryContainerLightMediumContrast,
  secondary = secondaryLightMediumContrast,
  onSecondary = onSecondaryLightMediumContrast,
  secondaryContainer = secondaryContainerLightMediumContrast,
  onSecondaryContainer = onSecondaryContainerLightMediumContrast,
  tertiary = tertiaryLightMediumContrast,
  onTertiary = onTertiaryLightMediumContrast,
  tertiaryContainer = tertiaryContainerLightMediumContrast,
  onTertiaryContainer = onTertiaryContainerLightMediumContrast,
  error = errorLightMediumContrast,
  onError = onErrorLightMediumContrast,
  errorContainer = errorContainerLightMediumContrast,
  onErrorContainer = onErrorContainerLightMediumContrast,
  background = backgroundLightMediumContrast,
  onBackground = onBackgroundLightMediumContrast,
  surface = surfaceLightMediumContrast,
  onSurface = onSurfaceLightMediumContrast,
  surfaceVariant = surfaceVariantLightMediumContrast,
  onSurfaceVariant = onSurfaceVariantLightMediumContrast,
  outline = outlineLightMediumContrast,
  outlineVariant = outlineVariantLightMediumContrast,
  scrim = scrimLightMediumContrast,
  inverseSurface = inverseSurfaceLightMediumContrast,
  inverseOnSurface = inverseOnSurfaceLightMediumContrast,
  inversePrimary = inversePrimaryLightMediumContrast,
  surfaceDim = surfaceDimLightMediumContrast,
  surfaceBright = surfaceBrightLightMediumContrast,
  surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
  surfaceContainerLow = surfaceContainerLowLightMediumContrast,
  surfaceContainer = surfaceContainerLightMediumContrast,
  surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
  surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
)

private val highContrastLightColorScheme = lightColorScheme(
  primary = primaryLightHighContrast,
  onPrimary = onPrimaryLightHighContrast,
  primaryContainer = primaryContainerLightHighContrast,
  onPrimaryContainer = onPrimaryContainerLightHighContrast,
  secondary = secondaryLightHighContrast,
  onSecondary = onSecondaryLightHighContrast,
  secondaryContainer = secondaryContainerLightHighContrast,
  onSecondaryContainer = onSecondaryContainerLightHighContrast,
  tertiary = tertiaryLightHighContrast,
  onTertiary = onTertiaryLightHighContrast,
  tertiaryContainer = tertiaryContainerLightHighContrast,
  onTertiaryContainer = onTertiaryContainerLightHighContrast,
  error = errorLightHighContrast,
  onError = onErrorLightHighContrast,
  errorContainer = errorContainerLightHighContrast,
  onErrorContainer = onErrorContainerLightHighContrast,
  background = backgroundLightHighContrast,
  onBackground = onBackgroundLightHighContrast,
  surface = surfaceLightHighContrast,
  onSurface = onSurfaceLightHighContrast,
  surfaceVariant = surfaceVariantLightHighContrast,
  onSurfaceVariant = onSurfaceVariantLightHighContrast,
  outline = outlineLightHighContrast,
  outlineVariant = outlineVariantLightHighContrast,
  scrim = scrimLightHighContrast,
  inverseSurface = inverseSurfaceLightHighContrast,
  inverseOnSurface = inverseOnSurfaceLightHighContrast,
  inversePrimary = inversePrimaryLightHighContrast,
  surfaceDim = surfaceDimLightHighContrast,
  surfaceBright = surfaceBrightLightHighContrast,
  surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
  surfaceContainerLow = surfaceContainerLowLightHighContrast,
  surfaceContainer = surfaceContainerLightHighContrast,
  surfaceContainerHigh = surfaceContainerHighLightHighContrast,
  surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
)

private val mediumContrastDarkColorScheme = darkColorScheme(
  primary = primaryDarkMediumContrast,
  onPrimary = onPrimaryDarkMediumContrast,
  primaryContainer = primaryContainerDarkMediumContrast,
  onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
  secondary = secondaryDarkMediumContrast,
  onSecondary = onSecondaryDarkMediumContrast,
  secondaryContainer = secondaryContainerDarkMediumContrast,
  onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
  tertiary = tertiaryDarkMediumContrast,
  onTertiary = onTertiaryDarkMediumContrast,
  tertiaryContainer = tertiaryContainerDarkMediumContrast,
  onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
  error = errorDarkMediumContrast,
  onError = onErrorDarkMediumContrast,
  errorContainer = errorContainerDarkMediumContrast,
  onErrorContainer = onErrorContainerDarkMediumContrast,
  background = backgroundDarkMediumContrast,
  onBackground = onBackgroundDarkMediumContrast,
  surface = surfaceDarkMediumContrast,
  onSurface = onSurfaceDarkMediumContrast,
  surfaceVariant = surfaceVariantDarkMediumContrast,
  onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
  outline = outlineDarkMediumContrast,
  outlineVariant = outlineVariantDarkMediumContrast,
  scrim = scrimDarkMediumContrast,
  inverseSurface = inverseSurfaceDarkMediumContrast,
  inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
  inversePrimary = inversePrimaryDarkMediumContrast,
  surfaceDim = surfaceDimDarkMediumContrast,
  surfaceBright = surfaceBrightDarkMediumContrast,
  surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
  surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
  surfaceContainer = surfaceContainerDarkMediumContrast,
  surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
  surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
)

private val highContrastDarkColorScheme = darkColorScheme(
  primary = primaryDarkHighContrast,
  onPrimary = onPrimaryDarkHighContrast,
  primaryContainer = primaryContainerDarkHighContrast,
  onPrimaryContainer = onPrimaryContainerDarkHighContrast,
  secondary = secondaryDarkHighContrast,
  onSecondary = onSecondaryDarkHighContrast,
  secondaryContainer = secondaryContainerDarkHighContrast,
  onSecondaryContainer = onSecondaryContainerDarkHighContrast,
  tertiary = tertiaryDarkHighContrast,
  onTertiary = onTertiaryDarkHighContrast,
  tertiaryContainer = tertiaryContainerDarkHighContrast,
  onTertiaryContainer = onTertiaryContainerDarkHighContrast,
  error = errorDarkHighContrast,
  onError = onErrorDarkHighContrast,
  errorContainer = errorContainerDarkHighContrast,
  onErrorContainer = onErrorContainerDarkHighContrast,
  background = backgroundDarkHighContrast,
  onBackground = onBackgroundDarkHighContrast,
  surface = surfaceDarkHighContrast,
  onSurface = onSurfaceDarkHighContrast,
  surfaceVariant = surfaceVariantDarkHighContrast,
  onSurfaceVariant = onSurfaceVariantDarkHighContrast,
  outline = outlineDarkHighContrast,
  outlineVariant = outlineVariantDarkHighContrast,
  scrim = scrimDarkHighContrast,
  inverseSurface = inverseSurfaceDarkHighContrast,
  inverseOnSurface = inverseOnSurfaceDarkHighContrast,
  inversePrimary = inversePrimaryDarkHighContrast,
  surfaceDim = surfaceDimDarkHighContrast,
  surfaceBright = surfaceBrightDarkHighContrast,
  surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
  surfaceContainerLow = surfaceContainerLowDarkHighContrast,
  surfaceContainer = surfaceContainerDarkHighContrast,
  surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
  surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
)

/**
 * @see app.campfire.core.model.Tent.Yellow
 */
val AltYellowColorPalette = ColorPalette(
  lightScheme,
  darkScheme,
  mediumContrastLightColorScheme,
  highContrastLightColorScheme,
  mediumContrastDarkColorScheme,
  highContrastDarkColorScheme,
)
