package app.campfire.ui.theming.db.mapping

import androidx.compose.material3.ColorScheme
import app.campfire.themes.SelectAllThemes
import app.campfire.themes.SelectThemeForKey
import app.campfire.ui.theming.theme.ComputedTheme
import com.r0adkll.swatchbuckler.compose.Theme

fun SelectThemeForKey.asDomainTheme(): ComputedTheme {
  return ComputedTheme(
    key = key,
    cacheKey = cacheKey,
    theme = Theme(
      lightColorScheme = ColorScheme(
        light_primaryColor,
        light_onPrimary,
        light_primaryContainer,
        light_onPrimaryContainer,
        light_inversePrimary,
        light_secondary,
        light_onSecondary,
        light_secondaryContainer,
        light_onSecondaryContainer,
        light_tertiary,
        light_onTertiary,
        light_tertiaryContainer,
        light_onTertiaryContainer,
        light_background,
        light_onBackground,
        light_surface,
        light_onSurface,
        light_surfaceVariant,
        light_onSurfaceVariant,
        light_surfaceTint,
        light_inverseSurface,
        light_inverseOnSurface,
        light_error,
        light_onError,
        light_errorContainer,
        light_onErrorContainer,
        light_outline,
        light_outlineVariant,
        light_scrim,
        light_surfaceBright,
        light_surfaceDim,
        light_surfaceContainer,
        light_surfaceContainerHigh,
        light_surfaceContainerHighest,
        light_surfaceContainerLow,
        light_surfaceContainerLowest,
        light_primaryFixed,
        light_primaryFixedDim,
        light_onPrimaryFixed,
        light_onPrimaryFixedVariant,
        light_secondaryFixed,
        light_secondaryFixedDim,
        light_onSecondaryFixed,
        light_onSecondaryFixedVariant,
        light_tertiaryFixed,
        light_tertiaryFixedDim,
        light_onTertiaryFixed,
        light_onTertiaryFixedVariant,
      ),
      darkColorScheme = ColorScheme(
        dark_primaryColor,
        dark_onPrimary,
        dark_primaryContainer,
        dark_onPrimaryContainer,
        dark_inversePrimary,
        dark_secondary,
        dark_onSecondary,
        dark_secondaryContainer,
        dark_onSecondaryContainer,
        dark_tertiary,
        dark_onTertiary,
        dark_tertiaryContainer,
        dark_onTertiaryContainer,
        dark_background,
        dark_onBackground,
        dark_surface,
        dark_onSurface,
        dark_surfaceVariant,
        dark_onSurfaceVariant,
        dark_surfaceTint,
        dark_inverseSurface,
        dark_inverseOnSurface,
        dark_error,
        dark_onError,
        dark_errorContainer,
        dark_onErrorContainer,
        dark_outline,
        dark_outlineVariant,
        dark_scrim,
        dark_surfaceBright,
        dark_surfaceDim,
        dark_surfaceContainer,
        dark_surfaceContainerHigh,
        dark_surfaceContainerHighest,
        dark_surfaceContainerLow,
        dark_surfaceContainerLowest,
        dark_primaryFixed,
        dark_primaryFixedDim,
        dark_onPrimaryFixed,
        dark_onPrimaryFixedVariant,
        dark_secondaryFixed,
        dark_secondaryFixedDim,
        dark_onSecondaryFixed,
        dark_onSecondaryFixedVariant,
        dark_tertiaryFixed,
        dark_tertiaryFixedDim,
        dark_onTertiaryFixed,
        dark_onTertiaryFixedVariant,
      ),
    ),
  )
}

fun SelectAllThemes.asDomainTheme(): ComputedTheme {
  return ComputedTheme(
    key = key,
    cacheKey = cacheKey,
    theme = Theme(
      lightColorScheme = ColorScheme(
        light_primaryColor,
        light_onPrimary,
        light_primaryContainer,
        light_onPrimaryContainer,
        light_inversePrimary,
        light_secondary,
        light_onSecondary,
        light_secondaryContainer,
        light_onSecondaryContainer,
        light_tertiary,
        light_onTertiary,
        light_tertiaryContainer,
        light_onTertiaryContainer,
        light_background,
        light_onBackground,
        light_surface,
        light_onSurface,
        light_surfaceVariant,
        light_onSurfaceVariant,
        light_surfaceTint,
        light_inverseSurface,
        light_inverseOnSurface,
        light_error,
        light_onError,
        light_errorContainer,
        light_onErrorContainer,
        light_outline,
        light_outlineVariant,
        light_scrim,
        light_surfaceBright,
        light_surfaceDim,
        light_surfaceContainer,
        light_surfaceContainerHigh,
        light_surfaceContainerHighest,
        light_surfaceContainerLow,
        light_surfaceContainerLowest,
        light_primaryFixed,
        light_primaryFixedDim,
        light_onPrimaryFixed,
        light_onPrimaryFixedVariant,
        light_secondaryFixed,
        light_secondaryFixedDim,
        light_onSecondaryFixed,
        light_onSecondaryFixedVariant,
        light_tertiaryFixed,
        light_tertiaryFixedDim,
        light_onTertiaryFixed,
        light_onTertiaryFixedVariant,
      ),
      darkColorScheme = ColorScheme(
        dark_primaryColor,
        dark_onPrimary,
        dark_primaryContainer,
        dark_onPrimaryContainer,
        dark_inversePrimary,
        dark_secondary,
        dark_onSecondary,
        dark_secondaryContainer,
        dark_onSecondaryContainer,
        dark_tertiary,
        dark_onTertiary,
        dark_tertiaryContainer,
        dark_onTertiaryContainer,
        dark_background,
        dark_onBackground,
        dark_surface,
        dark_onSurface,
        dark_surfaceVariant,
        dark_onSurfaceVariant,
        dark_surfaceTint,
        dark_inverseSurface,
        dark_inverseOnSurface,
        dark_error,
        dark_onError,
        dark_errorContainer,
        dark_onErrorContainer,
        dark_outline,
        dark_outlineVariant,
        dark_scrim,
        dark_surfaceBright,
        dark_surfaceDim,
        dark_surfaceContainer,
        dark_surfaceContainerHigh,
        dark_surfaceContainerHighest,
        dark_surfaceContainerLow,
        dark_surfaceContainerLowest,
        dark_primaryFixed,
        dark_primaryFixedDim,
        dark_onPrimaryFixed,
        dark_onPrimaryFixedVariant,
        dark_secondaryFixed,
        dark_secondaryFixedDim,
        dark_onSecondaryFixed,
        dark_onSecondaryFixedVariant,
        dark_tertiaryFixed,
        dark_tertiaryFixedDim,
        dark_onTertiaryFixed,
        dark_onTertiaryFixedVariant,
      ),
    ),
  )
}
