#!/bin/sh

echo "**** Running Pre-Push Check ****"

git stash -q --keep-index

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
"$SCRIPT_DIR/ktlint" --check
status=$?

git stash pop -q

echo "**** Pre-Push Check Finished ****"

exit $status
