#!/bin/sh

echo "**** Running Pre-Push Check ****"

git stash -q --keep-index

REPO_ROOT="$(git rev-parse --show-toplevel)"
"$REPO_ROOT/scripts/ktlint" --check
status=$?

git stash pop -q

echo "**** Pre-Push Check Finished ****"

exit $status
