package app.campfire.audioplayer.impl.util

import androidx.media3.common.Player

internal const val AUDIO_TAG = "AudioPlayer"
internal const val EVENTS_TAG = "Player.Listener.Events"

internal fun Int.eventAsDebugLog(): String = when (this) {
  Player.EVENT_TIMELINE_CHANGED -> "EVENT_TIMELINE_CHANGED"
  Player.EVENT_MEDIA_ITEM_TRANSITION -> "EVENT_MEDIA_ITEM_TRANSITION"
  Player.EVENT_TRACKS_CHANGED -> "EVENT_TRACKS_CHANGED"
  Player.EVENT_IS_LOADING_CHANGED -> "EVENT_IS_LOADING_CHANGED"
  Player.EVENT_PLAYBACK_STATE_CHANGED -> "EVENT_PLAYBACK_STATE_CHANGED"
  Player.EVENT_PLAY_WHEN_READY_CHANGED -> "EVENT_PLAY_WHEN_READY_CHANGED"
  Player.EVENT_PLAYBACK_SUPPRESSION_REASON_CHANGED -> "EVENT_PLAYBACK_SUPPRESSION_REASON_CHANGED"
  Player.EVENT_IS_PLAYING_CHANGED -> "EVENT_IS_PLAYING_CHANGED"
  Player.EVENT_REPEAT_MODE_CHANGED -> "EVENT_REPEAT_MODE_CHANGED"
  Player.EVENT_SHUFFLE_MODE_ENABLED_CHANGED -> "EVENT_SHUFFLE_MODE_ENABLED_CHANGED"
  Player.EVENT_PLAYER_ERROR -> "EVENT_PLAYER_ERROR"
  Player.EVENT_POSITION_DISCONTINUITY -> "EVENT_POSITION_DISCONTINUITY"
  Player.EVENT_PLAYBACK_PARAMETERS_CHANGED -> "EVENT_PLAYBACK_PARAMETERS_CHANGED"
  Player.EVENT_AVAILABLE_COMMANDS_CHANGED -> "EVENT_AVAILABLE_COMMANDS_CHANGED"
  Player.EVENT_MEDIA_METADATA_CHANGED -> "EVENT_MEDIA_METADATA_CHANGED"
  Player.EVENT_PLAYLIST_METADATA_CHANGED -> "EVENT_PLAYLIST_METADATA_CHANGED"
  Player.EVENT_SEEK_BACK_INCREMENT_CHANGED -> "EVENT_SEEK_BACK_INCREMENT_CHANGED"
  Player.EVENT_SEEK_FORWARD_INCREMENT_CHANGED -> "EVENT_SEEK_FORWARD_INCREMENT_CHANGED"
  Player.EVENT_MAX_SEEK_TO_PREVIOUS_POSITION_CHANGED -> "EVENT_MAX_SEEK_TO_PREVIOUS_POSITION_CHANGED"
  Player.EVENT_TRACK_SELECTION_PARAMETERS_CHANGED -> "EVENT_TRACK_SELECTION_PARAMETERS_CHANGED"
  Player.EVENT_AUDIO_ATTRIBUTES_CHANGED -> "EVENT_AUDIO_ATTRIBUTES_CHANGED"
  Player.EVENT_AUDIO_SESSION_ID -> "EVENT_AUDIO_SESSION_ID"
  Player.EVENT_VOLUME_CHANGED -> "EVENT_VOLUME_CHANGED"
  Player.EVENT_SKIP_SILENCE_ENABLED_CHANGED -> "EVENT_SKIP_SILENCE_ENABLED_CHANGED"
  Player.EVENT_SURFACE_SIZE_CHANGED -> "EVENT_SURFACE_SIZE_CHANGED"
  Player.EVENT_VIDEO_SIZE_CHANGED -> "EVENT_VIDEO_SIZE_CHANGED"
  Player.EVENT_RENDERED_FIRST_FRAME -> "EVENT_RENDERED_FIRST_FRAME"
  Player.EVENT_CUES -> "EVENT_CUES"
  Player.EVENT_METADATA -> "EVENT_METADATA"
  Player.EVENT_DEVICE_INFO_CHANGED -> "EVENT_DEVICE_INFO_CHANGED"
  Player.EVENT_DEVICE_VOLUME_CHANGED -> "EVENT_DEVICE_VOLUME_CHANGED"
  else -> "Unknown[$this]"
}

internal val Player.playbackStateAsDebugLog: String get() = when (playbackState) {
  Player.STATE_IDLE -> "STATE_IDLE"
  Player.STATE_BUFFERING -> "STATE_BUFFERING"
  Player.STATE_READY -> "STATE_READY"
  Player.STATE_ENDED -> "STATE_ENDED"
  else -> "Unknown[$playbackState]"
}
