name: Baseline profile generation

on:
  # Every Sunday at 00:43
  schedule:
    - cron: '43 0 * * 0'
  workflow_dispatch:
  pull_request:
    paths:
      - 'app/baselineprofile/**'
      - '.github/workflows/baseline-profile.yml'

env:
  ANDROID_PROFILE: pixel_7
  ANDROID_TARGET: google_apis
  ANDROID_API_LEVEL: 35
  ANDROID_ARCH: x86_64

jobs:
  # Build the app and benchmark tests and cache them in the setup-gradle task
  build:
    name: "Build App and Benchmark"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-write-only: true

      - name: Download Service Accounts
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo $GOOGLE_SERVICES_JSON > app/android/google-services.json

      - name: Build app and benchmark
        run: ./gradlew assembleNonMinifiedRelease --scan
        env:
          ORG_GRADLE_PROJECT_CAMPFIRE_SERVER_URL: ${{ secrets.SERVER_URL }}
          ORG_GRADLE_PROJECT_CAMPFIRE_USERNAME: ${{ secrets.TEST_USER_NAME }}
          ORG_GRADLE_PROJECT_CAMPFIRE_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

  # Run the baseline profile against the emulator
  baseline-profile:
    name: "Generate Baseline Profiles"
    needs: [build]
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Setup swap
        run: |
          sudo swapon --show
          sudo swapoff -a
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon -s

      - name: Free up disk space
        run: |
          sudo apt purge -yq $(dpkg -l | grep '^ii' | awk '{ print $2 }' | grep -P '(aspnetcore|cabal-|dotnet-|ghc-|libmono|mongodb-|mysql-|php)') \
            firefox google-chrome-stable google-cloud-cli microsoft-edge-stable mono-devel mono-runtime-common monodoc-manual powershell ruby
          sudo apt autoremove -yq
          sudo apt clean
          sudo rm -fr /opt/ghc /opt/hostedtoolcache /opt/az /opt/microsoft /opt/google /usr/lib/node_modules /usr/local/share/boost /usr/share/dotnet /usr/share/swift

      - uses: actions/checkout@v5
        with:
          # We need to use a Personal Access Token from an admin to be able to commit to main,
          # as it is a protected branch.
          # https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token#creating-a-fine-grained-personal-access-token
          token: ${{ secrets.CAMPFIRE_BOT_PAT }}

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: true

      - name: Download Service Accounts
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo $GOOGLE_SERVICES_JSON > app/android/google-services.json

#      - name: AVD cache
#        uses: actions/cache@v4
#        id: avd-cache
#        with:
#          path: |
#            ~/.android/avd/*
#            ~/.android/adb*
#          key: avd-${{ env.ANDROID_API_LEVEL }}

      - name: Generate Baseline Profiles
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.ANDROID_API_LEVEL }}
          target: ${{ env.ANDROID_TARGET }}
          arch: ${{ env.ANDROID_ARCH }}
          profile: ${{ env.ANDROID_PROFILE }}
          script: ./gradlew generateBaselineProfile --scan -Pandroid.testInstrumentationRunnerArguments.androidx.benchmark.enabledRules=BaselineProfile
        env:
          ORG_GRADLE_PROJECT_CAMPFIRE_SERVER_URL: ${{ secrets.SERVER_URL }}
          ORG_GRADLE_PROJECT_CAMPFIRE_USERNAME: ${{ secrets.TEST_USER_NAME }}
          ORG_GRADLE_PROJECT_CAMPFIRE_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

      # Use the Gradle Managed Devices to run the emulators for this test
#      - name: Generate Baseline Profiles
#        run: ./gradlew generateBaselineProfile --scan -Pandroid.testInstrumentationRunnerArguments.androidx.benchmark.enabledRules=BaselineProfile
#        env:
#          ORG_GRADLE_PROJECT_CAMPFIRE_SERVER_URL: ${{ secrets.SERVER_URL }}
#          ORG_GRADLE_PROJECT_CAMPFIRE_USERNAME: ${{ secrets.TEST_USER_NAME }}
#          ORG_GRADLE_PROJECT_CAMPFIRE_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

      # If we're on main branch, copy over the baseline profile and
      # commit it to the repository (if changed)
      - name: Commit baseline profile into main
        if: github.ref == 'refs/heads/main'
        run: |
          # If the baseline profile has changed, commit it
          if [[ $(git diff --stat app/android/src) != '' ]]; then
            git config user.name Rotom-Bot
            git config user.email veedubusc+deckbox@gmail.com
            git add app/android/src
            git commit -m "Update app baseline profile"
            git pull --rebase
            git push
          fi

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: reports
          path: |
            **/build/reports/*
